# Dockerfile.django
FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Статические файлы
RUN mkdir -p /app/staticfiles

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
